### ISSUE TITLE
Make option to invert motiongrams as a color option

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#87] opened 2020-02-13 14:41 UTC

**Comment by balintlaczko** [comment] 2020-02-24 02:01
Since the motion image was never inverting the way everything else did when selecting "invert colors" (not a bug - a feature!), I decided to invert the resulting matrix based on this setting. If we don't like this, we can debate and reopen this issue, until then I close it.

**Closed as completed by balintlaczko** 2020-02-24 02:01 UTC
Labels: enhancement
